package uk.curryGenerator;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.plaf.ComponentUI;

/**
 * screen for adding a new recipe to the mongo database
 * @author Jenny
 * @author thirdratecyberpunk
 *
 */
public class RecipeAdder {

	// frame TODO: improve this documentation
	private JFrame frame;
	// label explaining purpose of screen
	private JLabel title;
	// label explaining name input
	private JLabel curryName;
	// input for name of recipe being entered
	private JTextArea userCurry;
	// label explaining checkboxes
	private JLabel ingredients;
	// label explaining recipe input
	private JLabel recipe;
	// input for steps in making curry
	private JTextArea userRecipe;
	// label explaining strength rating
	private JLabel strength;
	// input for strength of curry
	private JTextArea userStrength;
	// submits given recipe to database
	private JButton submit;
	// returns user to the main menu
	private JButton cancel;
	// panel containing ingredients
	private JPanel middle;

	public RecipeAdder(){

		//Set up components for the frame
		title = new JLabel();
		curryName = new JLabel("Curry Name:");
		userCurry = new JTextArea();
		ingredients = new JLabel("Ingredients:");
		recipe = new JLabel("Recipe:");
		//TODO: replace this with a series of text fields which the user can spawn in to add more stages to the recipe
		userRecipe = new JTextArea(10, 30);
		//TODO: replace this with a slider or 5 star rating
		strength = new JLabel("Strength 1-5");
		userStrength = new JTextArea(1,5);
		submit = new JButton("Submit");
		cancel = new JButton("Cancel");

		//Set up initial frame
		frame = new JFrame("Recipe Adder");

		//Set up the panels from the components
		JPanel top = new JPanel(new BorderLayout());
		middle = IngredientsCheckBoxGenerator.ingredientsCheckBox();
		JPanel bottom = new JPanel(new GridBagLayout());

		//Initialise the frames layout
		frame.setLayout(new BorderLayout());

		//Add components to the top
		top.add(title, BorderLayout.NORTH);
		top.add(curryName, BorderLayout.CENTER);
		top.add(userCurry, BorderLayout.SOUTH);

		// middle components are generated by IngredientsCheckBoxGenerator

		//Add components to the bottom
		GridBagConstraints bottomConstraints = new GridBagConstraints();
		bottomConstraints.gridx = 0;
		bottomConstraints.gridy = 0;
		//TODO: tidy up this implementation, but not amazingly important
		bottom.add(recipe, bottomConstraints);
		bottomConstraints.gridy += 5;
		bottom.add(userRecipe, bottomConstraints);
		bottomConstraints.gridy += 5;
		bottom.add(strength, bottomConstraints);
		bottomConstraints.gridy += 5;
		bottom.add(userStrength, bottomConstraints);
		bottomConstraints.gridy += 5;
		bottom.add(submit, bottomConstraints);
		bottomConstraints.gridy += 5;
		bottom.add(cancel, bottomConstraints);

		//Add the panels to the frame
		frame.add(top, BorderLayout.NORTH);
		frame.add(middle, BorderLayout.CENTER);
		frame.add(bottom, BorderLayout.SOUTH);

		//Set the buttons
		cancel.addActionListener(new CancelActionListener());
		submit.addActionListener(new SubmitActionListener());

		//Initialising the frame
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.pack();
		frame.setSize(500, 500);
		frame.setVisible(true);
	}

	class CancelActionListener implements ActionListener{

		public void actionPerformed(ActionEvent e) {
			frame.dispose();

		}
	}

	class SubmitActionListener implements ActionListener{

		public void actionPerformed(ActionEvent e) {
			String name = userCurry.getText();
			System.out.println(name);
			ArrayList<String> ingredients = new ArrayList<String>();
			// checks if any checkboxes are ticked
			for (Component checkbox : middle.getComponents()) {
				// this check might be unneeded as the middle should only be checkboxes, but safety 
				if (checkbox instanceof JCheckBox){
					if (((AbstractButton) checkbox).isSelected()){
						ingredients.add( ((AbstractButton) checkbox).getText());
					}
				}
			}
			System.out.print(ingredients);
			ArrayList<String> steps = new ArrayList<String>();
			steps.add(userRecipe.getText());
			System.out.println(steps);
			int strength = Integer.parseInt(userStrength.getText());
			System.out.println(strength);
			//submit the recipe to the database
			MongoConnector mc = new MongoConnector();
			mc.addNewRecipe(name, ingredients, steps, strength);
			frame.dispose();
		}
	}
}
